---
title: "French Revolution Replication"
author: "Sharon Hui and Mark Oussoren"
date: "04/02/2022"
output:
  pdf_document:
    number_sections: yes
    extra_dependencies: ["float", "subfig"]
bibliography: bib.bib
citation_package: biblatex
biblio-style: ieee
header-includes:
- \usepackage{subfig}
- \usepackage{placeins}
- \usepackage{float}
- \floatplacement{figure}{H}
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE, cache = FALSE}
# load in useful packages
library(ggplot2)
library(corrplot)
library(ggpubr)
library(gridExtra)
library(plotly)
library(tidyverse)
library(foreign)
library(patchwork)
library(RColorBrewer)
library(class)
library(caret)
library(cowplot)
library(dplyr)

# set default knitr chunk
knitr::opts_chunk$set(
  echo = FALSE, 
  warning = FALSE, 
  message = FALSE,  
  cache = FALSE, 
  fig.width = 4,  
  fig.height = 2.25, 
  out.height = '75%',
  out.width = '75%', 
  fig.align = "center",  
  fig.pos = "h")

knitr::knit_hooks$set(plot = function(x, options)  {
  paste0(knitr::hook_plot_tex(x, options), "\n\\FloatBarrier\n")
})

# set working directory
setwd("~/230-Project/")

# load R files
source('R/table.R')

# load french data
french_main <- read.dta("dta/french_main.dta")
french_t5 <- read.dta("dta/french_t5.dta")
```


```{r}
ggplot(data = french_main) + geom_point(aes(x = year, y = totalpop, color = name)) + 
  xlab("Year") + ylab("Total Population") + 
  labs(color = "Location") + theme(text = element_text(size = 7),
        legend.position = "bottom") 
```

```{r}
a <- c("Rhineland", "Bavarian Palatinate", "Mark", "Westphalia without Mark",
       "Brunswick", "Saxony Province", "Hessen-Kassel", "Hanover")

b = c("Baden", "Bavaria Old", "Hessen-Darmstadt, right of the Rhine",
      "Saxony", "Wuerttemberg")

c = c( "Brandenburg", "East Prussia", "Pomerania without Swedish Pomerania",
       "Silesia", "Mecklenburg-Schwerin", "Schleswig-Holstein" )

colSummary <- function(data) {
  # compute urbrate 1700-1900 avg
  years <- c(1700, 1750, 1800, 1850, 1875, 1900)
  urb_avgs <- c()
  for (yr in years) {
    urb_df <- data %>% filter(year == yr) %>% group_by(name) %>%
      summarise(first_urbrate = first(urbrate),
                first_pop = first(totalpop1750)) %>%
      mutate(weighted_sum = (first_urbrate * first_pop))
    urb_avg <- sum(urb_df$weighted_sum / sum(urb_df$first_pop))
    SSR <- sum((urb_df$first_pop * (urb_df$first_urbrate - urb_avg)^2))
    N <- length(urb_df$first_urbrate)
    urb_sdv <- sqrt(N * SSR / ((N - 1) * sum(urb_df$first_pop)))
    urb_avgs <- c(urb_avgs, urb_avg, urb_sdv)
  }
  
  # compute share protestant avg
  protestant_df <- data %>% group_by(name) %>% 
    summarise(first_protestant = first(protestant),
              first_pop = first(totalpop1750)) %>%
    mutate(weighted_sum = (first_protestant * first_pop))
  protestant_avg <- sum(protestant_df$weighted_sum / sum(protestant_df$first_pop))
  SSR <- sum((protestant_df$first_pop *
                (protestant_df$first_protestant - protestant_avg)^2))
  N <- length(protestant_df$first_protestant)
  protestant_sdv <- sqrt(N * SSR / ((N - 1) * sum(protestant_df$first_pop)))

  # compute latitude avg
  lat_df <- data %>% group_by(name) %>% 
    summarise(first_lat = first(latitude),
              first_pop = first(totalpop1750)) %>%
    mutate(weighted_sum = (first_lat * first_pop))
  lat_avg <- sum(lat_df$weighted_sum / sum(lat_df$first_pop))
  SSR <- sum((lat_df$first_pop *
                (lat_df$first_lat - lat_avg)^2))
  N <- length(lat_df$first_lat)
  lat_sdv <- sqrt(N * SSR / ((N - 1) * sum(lat_df$first_pop)))
  
  # compute longitude avg
  long_df <- data %>% group_by(name) %>% 
    summarise(first_long = first(longitude),
          first_pop = first(totalpop1750)) %>%
    mutate(weighted_sum = (first_long * first_pop))
  long_avg <- sum(long_df$weighted_sum / sum(long_df$first_pop))
  SSR <- sum((long_df$first_pop *
              (long_df$first_long - long_avg)^2))
  N <- length(long_df$first_long)
  long_sdv <- sqrt(N * SSR / ((N - 1) * sum(long_df$first_pop)))

  # compute distance to paris avg
  paris_df <- data %>% group_by(name) %>% 
    summarise(first_dist = first(distpa),
          first_pop = first(totalpop1750)) %>%
    mutate(weighted_sum = (first_dist * first_pop))
  paris_avg <- sum(paris_df$weighted_sum / sum(paris_df$first_pop))
  SSR <- sum((paris_df$first_pop *
                (paris_df$first_dist - paris_avg)^2))
  N <- length(paris_df$first_dist)
  paris_sdv <- sqrt(N * SSR / ((N - 1) * sum(paris_df$first_pop)))
  
  return(c(urb_avgs, protestant_avg, protestant_sdv,
           lat_avg, lat_sdv, long_avg, long_sdv,
           paris_avg, paris_sdv))
}

# getting control west of elbe
first_col <- colSummary(na.omit(french_main) %>% filter(westelbe == 1))

# getting west of elbe control
second_col <- colSummary(na.omit(french_main) %>% filter(name %in% b))

# gettting treated
third_col <- colSummary(na.omit(french_main) %>% filter(name %in% a))

# getting all control
fourth_col <- colSummary(na.omit(french_main) %>% filter(name %in% c(b, c)))

# last column is everything
fifth_col <- colSummary(na.omit(french_main))

# combining into table
combined_avgs <- cbind(first_col, second_col, third_col, fourth_col,
                       fifth_col)
```

```{r}
row_names <- c('Urbanization in 1700', '', 'Urbanization in 1750', '',
               'Urbanization in 1800', '', 'Urbanization in 1850', '',
               'Urbanization in 1875', '', 'Urbanization in 1900', '',
               'Share Protestant', '', 'Latitude', '', 'Longitude', '',
               'Distance to Paris', '')
table_2 <- createTable(round(combined_avgs, 2), row_names)
```
