---
title: "table4"
author: "Sharon Hui"
date: "4/16/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Table 4


```{r}
library(dplyr)
library(foreign)
library(lfe)
library(lmtest)
library(car)
library(tidyr)
library(plm)

french_t5 = read.dta('french_t5.dta')
french_main = read.dta('french_main.dta')

a <- c("Rhineland", "Bavarian Palatinate", "Mark", "Westphalia without Mark",
       "Brunswick", "Saxony Province", "Hessen-Kassel", "Hanover")

b <- c("Baden", "Bavaria Old" , "Hessen-Darmstadt, right of the Rhine", 
      "Saxony", "Wuerttemberg")
c <- c( "Brandenburg" , "East Prussia" , 
       "Pomerania without Swedish Pomerania" , "Silesia",  
       "Mecklenburg-Schwerin" , "Schleswig-Holstein" )

keep = french_main %>%
  filter(year==1700 | year==1750 | year==1800 | year==1850 | year==1875 | year==1900 )

new_keep = (keep %>% filter(westelbe==1))
```




```{r}
each_id = data.frame( value = c('Years French presence x 1750', 
                                'SD Years French presence x 1750', 
                                'Years French presence x 1800', 
                                'SD Years French presence x 1800', 
                                'Years French presence x 1850', 
                                'SD Years French presence x 1850', 
                                'Years French presence x 1875', 
                                'SD Years French presence x 1875', 
                                'Years French presence x 1900',  
                                'SD Years French presence x 1900', 
                                'Lagged Urbanization', 
                                'SD Lagged Urbanization', 
                                'Observations', 
                                'Number of states', 
                                'p-value for joint signficance after 1800', 
                                'p-value for joint significance covariates') )
for (i in unique(new_keep$id)){
  
  table4_1 = new_keep %>%
    filter( id!= i )
  fe4_1 = felm(formula = urbrate ~ fpresence1750 + fpresence1800 + 
               fpresence1850 + fpresence1875 + fpresence1900 + 
               yr1700 + yr1750 + yr1800 + yr1850 + yr1875 | id | 0 | id, 
               data = table4_1, weights = table4_1$totalpop1750)
  
coef1 <- coeftest(fe4_1)
data_count <- dim(drop_na(table4_1))[1]
state_count <- length(unique(table4_1$name))
pval1 <- linearHypothesis(fe4_1, c("fpresence1850=0", 
                                   "fpresence1875=0", 
                                   "fpresence1900=0"),
                          test = c("F"))$`Pr(>F)`[2]
pval2 <- 0
col1 <- c(rbind(coef1[1:5, 1], coef1[1:5, 2]))
col1 <- c(col1, 0, 0, data_count, state_count, pval1, pval2)
  each_id = cbind(each_id, col1)
}
colnames(each_id ) = c('', paste('Removed ID', unique(new_keep$id)) )
each_id

```

