---
title: "table3"
author: "Sharon Hui"
date: "4/16/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
# install.packages('foreign')
library(foreign)
library(dplyr)
library(stringr)
library(kableExtra)
library(sandwich)
library(lmtest)
library(lfe)
library(dplyr)
library(tidyr)
library(broom)
library(lfe)
library(fixest)
french_t5 = read.dta('french_t5.dta')
french_main = read.dta('french_main.dta')

a <- c("Rhineland", "Bavarian Palatinate", "Mark", "Westphalia without Mark",
       "Brunswick", "Saxony Province", "Hessen-Kassel", "Hanover")

b <- c("Baden", "Bavaria Old" , "Hessen-Darmstadt, right of the Rhine", 
      "Saxony", "Wuerttemberg")
c <- c( "Brandenburg" , "East Prussia" , 
       "Pomerania without Swedish Pomerania" , "Silesia",  
       "Mecklenburg-Schwerin" , "Schleswig-Holstein" )

keep = french_main %>%
  filter(year==1700 | year==1750 | year==1800 | year==1850 | year==1875 | year==1900 )
```

```{r}
a_b = keep %>% filter(name %in% c(a, b) & year %in% c(1750, 1800, 1850, 1875, 1900)) %>%
  select(name, fpresence1750, fpresence1800,  fpresence1850, fpresence1875, fpresence1900, 
         totalpop1750,
         yr1700, yr1750, yr1800, yr1875) %>% 
  group_by(name) %>%
  summarise( fpresence1750 = sum(fpresence1750),
             fpresence1800 = sum(fpresence1800),
             fpresence1850 = sum(fpresence1850),
             fpresence1900 = sum(fpresence1900),
             totalpop1750 = first(totalpop1750)
             )
a_b = keep %>% filter( westelbe == 1) %>%
  select(id, urbrate, fpresence1750, fpresence1800,  
         fpresence1850, fpresence1875,  fpresence1900, totalpop1750,
         yr1700, yr1750, yr1800, yr1850,yr1875,
         yr1900 )

library(estimatr)
lm_robust(urbrate ~ fpresence1750 + fpresence1800 + 
           fpresence1850 + fpresence1900 + 
           yr1700 + yr1750 + yr1800 + yr1875, data=a_b,
          clusters = id, weights = totalpop1750,
          fixed_effects = id, `se_type` = "stata")

reg = lm(urbrate ~ fpresence1750 + fpresence1800 + 
           fpresence1850 + fpresence1900 + 
           yr1700 + yr1750 + yr1800 + yr1875, data=a_b, weights = totalpop1750)
v_both = vcovCL(reg, type='HC2', cluster = ~id)
coeftest(reg, v_both)
library(plm)
plm(urbrate ~ fpresence1750 + fpresence1800 + 
           fpresence1850 + fpresence1900 + 
           yr1700 + yr1750 + yr1800 + yr1875, data=a_b,
    index=c("id"), model="within", weights = totalpop1750)


felm(urbrate ~ fpresence1750 + fpresence1800 + 
           fpresence1850 + fpresence1900 + 
           yr1700 + yr1750 + yr1800 + yr1875 | id, data = a_b, weights = a_b$totalpop1750)
```




```{r}
col0 <- c("Years French presence × 1750", "(*)", "Years French presence × 1750", "(*)", "Years French × 1800 presence", "(*)", "Years French × 1850 presence", "(*)", "Years French presence × 1900", "(*)", "", "Observations", "Number of states", "p-value for joint significance after 1800")

fe1 = felm(formula = urbrate ~ fpresence1750 + fpresence1800 + 
           fpresence1850 + fpresence1875 + fpresence1900 + 
           yr1700 + yr1750 + yr1800 + yr1850 + yr1875 | id, 
     data = a_b, weights = a_b$totalpop1750)
res1 <- coeftest(fe1 , vcov = vcovHAC(fe1, type="HC1"))
col1 <- c(rbind(res1[1:5,1], res1[1:5,2]))
joint_pval1 <- 0
col1 <- c(col1, 0, dim(drop_na(a_b))[1], length(unique(a_b)), joint_pval1)
fe2 = felm(formula = urbrate ~ fpresence1750 + fpresence1800 + 
           fpresence1850 + fpresence1875 + fpresence1900 + 
           yr1700 + yr1750 + yr1800 + yr1850 + 
       yr1875 | id, 
     data = a_b )
res2 <- coeftest(fe2, vcov = vcovHAC(fe2, type="HC1"))
col2 <- c(rbind(res2[1:5,1], res2[1:5,2]))
joint_pval2 <- 0
col2 <- c(col2, 0, dim(drop_na(a_b))[1], length(unique(a_b)), joint_pval2)

fe3 = felm(formula = urbrate ~ fpresence1750 + fpresence1800 + 
           fpresence1850 + fpresence1875 + fpresence1900 + 
           yr1700 + yr1750 + yr1800 + yr1850 + yr1875 | factor(id), 
     data = keep, weights = keep$totalpop1750)
# vcovHC doesn't give the same standard errors
res3 <- coeftest(fe3 , vcov = vcovHC(fe3, type="HC0"))
col3 <- c(rbind(res3[1:5,1], res3[1:5,2]))
joint_pval3 <- 0
col3 <- c(col3, 0, dim(drop_na(keep))[1], length(unique(keep)), joint_pval3)

fe4 = felm(formula = urbrate ~ fpresence1750 + fpresence1800 + 
           fpresence1850 + fpresence1875 + fpresence1900 + 
           yr1700 + yr1750 + yr1800 + yr1850 + 
       yr1875 | id, 
     data = keep )
res4 <- coeftest(fe4, vcov = vcovHC(fe4, type="HC0"))
col4 <- c(rbind(res4[1:5,1], res4[1:5,2]))
joint_pval4 <- 0
col4 <- c(col4, 0, dim(drop_na(keep))[1], length(unique(keep)), joint_pval4)
```




```{r}
createTable(round(cbind(col1, col2, col3, col4), 3), col0)
```

